version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/initdb.d/:/docker-entrypoint-initdb.d/
      - ./docker/mysql/conf.d:/etc/mysql/conf.d/

  elasticsearch:
    container_name: elasticsearch
    build: ./docker/elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker/elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./docker/elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options

  redis:
    container_name: redis
    image: redis:5.0-alpine
    ports:
      - 6379:6379
