spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      client-id: worker-dev
      max-poll-records: 5
      group-id: worker-dev

    listener:
      client-id: worker-listener-dev
